=== e-scheiber/DistributedProgramming2/anexe/xml/schema/struct-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:mk="http://www.distr2.edu"
 targetNamespace="http://www.distr2.edu">

  <xsd:element name="structura">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="mk:disciplina"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="disciplina">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="mk:nume"/>
        <xsd:element ref="mk:fond-de-timp"/>
      </xsd:sequence>
      <xsd:attribute name="fel" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="nume" type="xsd:string"/>

  <xsd:element name="fond-de-timp">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element ref="mk:curs"/>
        <xsd:element ref="mk:seminar"/>
        <xsd:element ref="mk:laborator"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="curs" type="xsd:string"/>

  <xsd:element name="seminar" type="xsd:string"/>

  <xsd:element name="laborator" type="xsd:string"/>
</xsd:schema>

=== e-scheiber/DistributedProgramming2/anexe/xml/schema/struct.xml
<?xml version="1.0" encoding="UTF-8"?>
<mk:structura xmlns:mk="http://www.distr2.edu" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.distr2.edu struct-schema.xsd">
 
  <mk:disciplina fel="obligatoriu">
    <mk:nume> Analiza numerica </mk:nume>
    <mk:fond-de-timp>
       <mk:curs>2</mk:curs>
       <mk:seminar>1</mk:seminar>
       <mk:laborator>1</mk:laborator>
    </mk:fond-de-timp>
  </mk:disciplina>
  <mk:disciplina fel="obligatoriu">
    <mk:nume> Programare distribuita </mk:nume>
    <mk:fond-de-timp>
       <mk:curs>2</mk:curs>
       <mk:seminar>0</mk:seminar>
       <mk:laborator>2</mk:laborator>
    </mk:fond-de-timp>
  </mk:disciplina>
  <mk:disciplina fel="obligatoriu">
    <mk:nume> Soft matematic </mk:nume>
    <mk:fond-de-timp>
       <mk:curs>2</mk:curs>
       <mk:seminar>0</mk:seminar>
       <mk:laborator>1</mk:laborator>
    </mk:fond-de-timp>
  </mk:disciplina>
</mk:structura>
